name: automerge from develop to main branch
on:
  push:
    branches:
      - develop

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Configure Git
        run: |
          git config user.name "drdamitha"
          git config user.email "drdamitha@gmail.com"

      - name: Fetch latest from origin
        run: |
          git fetch origin

      - name: Checkout main branch
        run: |
          git checkout main
          git fetch origin main

      - name: Create commit with changes from develop
        run: |
          git merge origin/develop --allow-unrelated-histories --no-ff --allow-unrelated-histories -m "Auto merge from CI pipeline"

      - name: Push changes to main
        run: |
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
